const getDataDrinks = [
  {
    id: 1,
    nama: "Es Teh Manis",
    rating: 4.5,
    quantity: 50,
    reviewer: 300,
    harga: 10000,
    gambar: "https://example.com/images/estehmanis.jpg",
  },
  {
    id: 2,
    nama: "Cappuccino",
    rating: 4.7,
    quantity: 20,
    reviewer: 220,
    harga: 30000,
    gambar: "https://example.com/images/cappuccino.jpg",
  },
  {
    id: 3,
    nama: "Es Jeruk",
    rating: 4.3,
    quantity: 40,
    reviewer: 250,
    harga: 12000,
    gambar: "https://example.com/images/esjeruk.jpg",
  },
  {
    id: 4,
    nama: "Latte",
    rating: 4.6,
    quantity: 25,
    reviewer: 270,
    harga: 32000,
    gambar: "https://example.com/images/latte.jpg",
  },
  {
    id: 5,
    nama: "Es Cendol",
    rating: 4.4,
    quantity: 35,
    reviewer: 190,
    harga: 15000,
    gambar: "https://example.com/images/escendol.jpg",
  },
  {
    id: 6,
    nama: "Green Tea Matcha",
    rating: 4.5,
    quantity: 18,
    reviewer: 210,
    harga: 28000,
    gambar: "https://example.com/images/greentea.jpg",
  },
  {
    id: 7,
    nama: "Bandrek",
    rating: 4.3,
    quantity: 20,
    reviewer: 130,
    harga: 13000,
    gambar: "https://example.com/images/bandrek.jpg",
  },
  {
    id: 8,
    nama: "Espresso",
    rating: 4.6,
    quantity: 15,
    reviewer: 240,
    harga: 25000,
    gambar: "https://example.com/images/espresso.jpg",
  },
  {
    id: 9,
    nama: "Es Kelapa Muda",
    rating: 4.4,
    quantity: 30,
    reviewer: 200,
    harga: 18000,
    gambar: "https://example.com/images/eskelapa.jpg",
  },
  {
    id: 10,
    nama: "Hot Chocolate",
    rating: 4.5,
    quantity: 22,
    reviewer: 150,
    harga: 35000,
    gambar: "https://example.com/images/hotchocolate.jpg",
  },
  {
    id: 11,
    nama: "Teh Tarik",
    rating: 4.4,
    quantity: 25,
    reviewer: 190,
    harga: 12000,
    gambar: "https://example.com/images/tehtarik.jpg",
  },
  {
    id: 12,
    nama: "Smoothie Berry",
    rating: 4.7,
    quantity: 10,
    reviewer: 180,
    harga: 30000,
    gambar: "https://example.com/images/smoothieberry.jpg",
  },
  {
    id: 13,
    nama: "Kopi Tubruk",
    rating: 4.5,
    quantity: 27,
    reviewer: 260,
    harga: 15000,
    gambar: "https://example.com/images/kopitubruk.jpg",
  },
  {
    id: 14,
    nama: "Mojito Mocktail",
    rating: 4.3,
    quantity: 15,
    reviewer: 140,
    harga: 25000,
    gambar: "https://example.com/images/mojito.jpg",
  },
  {
    id: 15,
    nama: "Es Kopi Susu",
    rating: 4.6,
    quantity: 35,
    reviewer: 310,
    harga: 18000,
    gambar: "https://example.com/images/eskopisusu.jpg",
  },
  {
    id: 16,
    nama: "Lemon Tea",
    rating: 4.3,
    quantity: 40,
    reviewer: 200,
    harga: 15000,
    gambar: "https://example.com/images/lemontea.jpg",
  },
  {
    id: 17,
    nama: "Jus Alpukat",
    rating: 4.5,
    quantity: 18,
    reviewer: 220,
    harga: 17000,
    gambar: "https://example.com/images/jusalpukat.jpg",
  },
  {
    id: 18,
    nama: "Milkshake Vanilla",
    rating: 4.4,
    quantity: 12,
    reviewer: 160,
    harga: 25000,
    gambar: "https://example.com/images/milkshakevanilla.jpg",
  },
  {
    id: 19,
    nama: "Wedang Jahe",
    rating: 4.2,
    quantity: 28,
    reviewer: 140,
    harga: 12000,
    gambar: "https://example.com/images/wedangjahe.jpg",
  },
  {
    id: 20,
    nama: "Es Soda Gembira",
    rating: 4.3,
    quantity: 33,
    reviewer: 180,
    harga: 20000,
    gambar: "https://example.com/images/essodagembira.jpg",
  },
];

export { getDataDrinks };
