const getDataDrinks = [
  {
    id: 1,
    name: "Es Teh Manis",
    rating: 4.5,
    quantity: 50,
    reviewer: 300,
    price: "10000",
    image: "/drinks/esteh.jpg",
  },
  {
    id: 2,
    name: "Cappuccino",
    rating: 4.7,
    quantity: 20,
    reviewer: 220,
    price: "30000",
    image: "/drinks/cappucino.jpg",
  },
  {
    id: 3,
    name: "Es Jeruk",
    rating: 4.3,
    quantity: 40,
    reviewer: 250,
    price: "12000",
    image: "/drinks/esjeruk.jpg",
  },
  {
    id: 4,
    name: "Latte",
    rating: 4.6,
    quantity: 25,
    reviewer: 270,
    price: "32000",
    image: "/drinks/latte.jpg",
  },
  {
    id: 5,
    name: "Es Cendol",
    rating: 4.4,
    quantity: 35,
    reviewer: 190,
    price: "15000",
    image: "/drinks/escendol.jpg",
  },
  {
    id: 6,
    name: "Green Tea Matcha",
    rating: 4.5,
    quantity: 18,
    reviewer: 210,
    price: "28000",
    image: "/drinks/green-tea.jpg",
  },
  {
    id: 7,
    name: "Jus Kalamansi",
    rating: 4.3,
    quantity: 20,
    reviewer: 130,
    price: "13000",
    image: "/drinks/jus-kalamansi.jpg",
  },
  {
    id: 8,
    name: "Espresso",
    rating: 4.6,
    quantity: 15,
    reviewer: 240,
    price: "25000",
    image: "/drinks/espresso.jpg",
  },
  {
    id: 9,
    name: "Es Kelapa Muda",
    rating: 4.4,
    quantity: 30,
    reviewer: 200,
    price: "18000",
    image: "/drinks/eskelapa.jpg",
  },
  {
    id: 10,
    name: "Hot Chocolate",
    rating: 4.5,
    quantity: 22,
    reviewer: 150,
    price: "35000",
    image: "/drinks/hot-chocolate.jpg",
  },
  {
    id: 11,
    name: "Teh Tarik",
    rating: 4.4,
    quantity: 25,
    reviewer: 190,
    price: "12000",
    image: "/drinks/teh-tarik.jpg",
  },
  {
    id: 12,
    name: "Smoothie Berry",
    rating: 4.7,
    quantity: 10,
    reviewer: 180,
    price: "30000",
    image: "/drinks/smoothie-berry.jpg",
  },
  {
    id: 13,
    name: "Kopi Tubruk",
    rating: 4.5,
    quantity: 27,
    reviewer: 260,
    price: "15000",
    image: "/drinks/kopi-tubruk.jpg",  
  },
  {
    id: 14,
    name: "Mojito Mocktail",
    rating: 4.3,
    quantity: 15,
    reviewer: 140,
    price: "25000",
    image: "/drinks/mojito-mocktail.jpg",
  },
  {
    id: 15,
    name: "Es Kopi Susu",
    rating: 4.6,
    quantity: 35,
    reviewer: 310,
    price: "18000",
    image: "/drinks/eskopi-susu.jpg",
  },
  {
    id: 16,
    name: "Lemon Tea",
    rating: 4.3,
    quantity: 40,
    reviewer: 200,
    price: "15000",
    image: "/drinks/lemon-tea.jpg",
  },
  {
    id: 17,
    name: "Jus Alpukat",
    rating: 4.5,
    quantity: 18,
    reviewer: 220,
    price: "17000",
    image: "/drinks/jus-alpukat.jpg",
  },
  {
    id: 18,
    name: "Milkshake Vanilla",
    rating: 4.4,
    quantity: 12,
    reviewer: 160,
    price: "25000",
    image: "/drinks/milkshake-vanilla.jpg",
  },
  {
    id: 19,
    name: "Wedang Jahe",
    rating: 4.2,
    quantity: 28,
    reviewer: 140,
    price: "12000",
    image: "/drinks/wedang-jahe.jpg",
  },
  {
    id: 20,
    name: "Es Soda Gembira",
    rating: 4.3,
    quantity: 33,
    reviewer: 180,
    price: "20000",
    image: "/drinks/essoda-gembira.jpg",
  },
];

export { getDataDrinks };
