const getDataFoods = [
    {
      id: 1,
      nama: "Nasi Goreng Spesial",
      rating: 4.5,
      quantity: 10,
      reviewer: 230,
      harga: 35000,
    },
    {
      id: 2,
      nama: "Pasta Carbonara",
      rating: 4.2,
      quantity: 15,
      reviewer: 190,
      harga: 55000,
    },
    {
      id: 3,
      nama: "Sate Ayam Madura",
      rating: 4.6,
      quantity: 20,
      reviewer: 310,
      harga: 40000,
    },
    {
      id: 4,
      nama: "Beef Stroganoff",
      rating: 4.4,
      quantity: 12,
      reviewer: 175,
      harga: 70000,
    },
    {
      id: 5,
      nama: "Rendang Sapi",
      rating: 4.8,
      quantity: 8,
      reviewer: 290,
      harga: 65000,
    },
    {
      id: 6,
      nama: "Fish and Chips",
      rating: 4.3,
      quantity: 18,
      reviewer: 150,
      harga: 50000,
    },
    {
      id: 7,
      nama: "Ayam Betutu",
      rating: 4.5,
      quantity: 14,
      reviewer: 220,
      harga: 60000,
    },
    {
      id: 8,
      nama: "Lasagna Bolognese",
      rating: 4.2,
      quantity: 10,
      reviewer: 160,
      harga: 65000,
    },
    {
      id: 9,
      nama: "Gado-Gado",
      rating: 4.1,
      quantity: 25,
      reviewer: 130,
      harga: 30000,
    },
    {
      id: 10,
      nama: "Steak Frites",
      rating: 4.6,
      quantity: 9,
      reviewer: 210,
      harga: 75000,
    },
    {
      id: 11,
      nama: "Sop Buntut",
      rating: 4.4,
      quantity: 7,
      reviewer: 180,
      harga: 65000,
    },
    {
      id: 12,
      nama: "Paella",
      rating: 4.5,
      quantity: 13,
      reviewer: 200,
      harga: 85000,
    },
    {
      id: 13,
      nama: "Bakso Malang",
      rating: 4.3,
      quantity: 30,
      reviewer: 300,
      harga: 25000,
    },
    {
      id: 14,
      nama: "Pizza Margherita",
      rating: 4.7,
      quantity: 8,
      reviewer: 260,
      harga: 90000,
    },
    {
      id: 15,
      nama: "Mie Goreng Jawa",
      rating: 4.2,
      quantity: 22,
      reviewer: 150,
      harga: 28000,
    },
    {
      id: 16,
      nama: "Quiche Lorraine",
      rating: 4.1,
      quantity: 14,
      reviewer: 110,
      harga: 55000,
    },
    {
      id: 17,
      nama: "Soto Ayam",
      rating: 4.6,
      quantity: 17,
      reviewer: 280,
      harga: 30000,
    },
    {
      id: 18,
      nama: "Beef Wellington",
      rating: 4.5,
      quantity: 6,
      reviewer: 190,
      harga: 120000,
    },
    {
      id: 19,
      nama: "Es Campur",
      rating: 4.3,
      quantity: 35,
      reviewer: 140,
      harga: 20000,
    },
    {
      id: 20,
      nama: "Croissant Sandwich",
      rating: 4.4,
      quantity: 20,
      reviewer: 155,
      harga: 45000,
    },
];

export { getDataFoods };